LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

LOCAL_MODULE := 7zip
LOCAL_CPP_FEATURES := rtti exceptions

LOCAL_SRC_FILES := \
    CPP/7zip/Compress/Bcj2Coder.cpp \
    CPP/7zip/Compress/Bcj2Register.cpp \
    CPP/7zip/Compress/BcjCoder.cpp \
    CPP/7zip/Compress/BcjRegister.cpp \
    CPP/7zip/Compress/BranchMisc.cpp \
    CPP/7zip/Compress/BranchRegister.cpp \
    CPP/7zip/Compress/ByteSwap.cpp \
    CPP/7zip/Compress/CodecExports.cpp \
    CPP/7zip/Compress/CopyCoder.cpp \
    CPP/7zip/Compress/CopyRegister.cpp \
    CPP/7zip/Compress/DeltaFilter.cpp \
    CPP/7zip/Compress/Lzma2Decoder.cpp \
    CPP/7zip/Compress/Lzma2Encoder.cpp \
    CPP/7zip/Compress/Lzma2Register.cpp \
    CPP/7zip/Compress/LzmaDecoder.cpp \
    CPP/7zip/Compress/LzmaEncoder.cpp \
    CPP/7zip/Compress/LzmaRegister.cpp \
    CPP/7zip/Compress/PpmdDecoder.cpp \
    CPP/7zip/Compress/PpmdEncoder.cpp \
    CPP/7zip/Compress/PpmdRegister.cpp \
    CPP/7zip/Compress/XzDecoder.cpp \
    CPP/7zip/Compress/XzEncoder.cpp \
    CPP/7zip/Crypto/7zAes.cpp \
    CPP/7zip/Crypto/7zAesRegister.cpp \
    CPP/7zip/Crypto/MyAes.cpp \
    CPP/7zip/Crypto/MyAesReg.cpp \
    CPP/7zip/Crypto/RandGen.cpp \
    C/7zStream.c \
    C/Alloc.c \
    C/Bcj2.c \
    C/Bcj2Enc.c \
    C/Bra.c \
    C/Bra86.c \
    C/BraIA64.c \
    C/CpuArch.c \
    C/Delta.c \
    C/LzFind.c \
    C/LzFindOpt.c \
    C/LzFindMt.c \
    C/Lzma2Dec.c \
    C/Lzma2DecMt.c \
    C/LzmaDec.c \
    C/Lzma2Enc.c \
    C/LzmaEnc.c \
    C/MtCoder.c \
    C/MtDec.c \
    C/Ppmd7.c \
    C/Ppmd7Dec.c \
    C/Ppmd7Enc.c \
    C/Sha256.c \
    C/Sha256Opt.c \
    C/Sort.c \
    C/SwapBytes.c \
    C/Threads.c \
    C/Xz.c \
    C/XzDec.c \
    C/XzEnc.c \
    C/XzIn.c \
    C/Aes.c \
    C/AesOpt.c \
    C/7zCrc.c \
    C/7zCrcOpt.c \
    C/XzCrc64.c \
    C/XzCrc64Opt.c \
    CPP/Common/CRC.cpp \
    CPP/Common/CrcReg.cpp \
    CPP/Common/DynLimBuf.cpp \
    CPP/Common/IntToString.cpp \
    CPP/Common/LzFindPrepare.cpp \
    CPP/Common/MyString.cpp \
    CPP/Common/MyVector.cpp \
    CPP/Common/MyWindows.cpp \
    CPP/Common/NewHandler.cpp \
    CPP/Common/Sha256Prepare.cpp \
    CPP/Common/Sha256Reg.cpp \
    CPP/Common/StringConvert.cpp \
    CPP/Common/StringToInt.cpp \
    CPP/Common/UTFConvert.cpp \
    CPP/Common/Wildcard.cpp \
    CPP/Common/XzCrc64Init.cpp \
    CPP/Common/XzCrc64Reg.cpp \
    CPP/7zip/Common/CreateCoder.cpp \
    CPP/7zip/Common/CWrappers.cpp \
    CPP/7zip/Common/InBuffer.cpp \
    CPP/7zip/Common/InOutTempBuffer.cpp \
    CPP/7zip/Common/FilterCoder.cpp \
    CPP/7zip/Common/LimitedStreams.cpp \
    CPP/7zip/Common/LockedStream.cpp \
    CPP/7zip/Common/MethodId.cpp \
    CPP/7zip/Common/MethodProps.cpp \
    CPP/7zip/Common/OffsetStream.cpp \
    CPP/7zip/Common/OutBuffer.cpp \
    CPP/7zip/Common/ProgressUtils.cpp \
    CPP/7zip/Common/PropId.cpp \
    CPP/7zip/Common/StreamBinder.cpp \
    CPP/7zip/Common/StreamObjects.cpp \
    CPP/7zip/Common/StreamUtils.cpp \
    CPP/7zip/Common/UniqBlocks.cpp \
    CPP/7zip/Common/VirtThread.cpp \
    CPP/Windows/FileDir.cpp \
    CPP/Windows/FileFind.cpp \
    CPP/Windows/FileIO.cpp \
    CPP/Windows/FileName.cpp \
    CPP/Windows/PropVariant.cpp \
    CPP/Windows/PropVariantConv.cpp \
    CPP/Windows/Synchronization.cpp \
    CPP/Windows/System.cpp \
    CPP/Windows/TimeUtils.cpp \
    CPP/7zip/Archive/LzmaHandler.cpp \
    CPP/7zip/Archive/SplitHandler.cpp \
    CPP/7zip/Archive/XzHandler.cpp \
    CPP/7zip/Archive/ArchiveExports.cpp \
    CPP/7zip/Archive/DllExports2.cpp \
    CPP/7zip/Archive/Common/CoderMixer2.cpp \
    CPP/7zip/Archive/Common/DummyOutStream.cpp \
    CPP/7zip/Archive/Common/InStreamWithCRC.cpp \
    CPP/7zip/Archive/Common/ItemNameUtils.cpp \
    CPP/7zip/Archive/Common/MultiStream.cpp \
    CPP/7zip/Archive/Common/OutStreamWithCRC.cpp \
    CPP/7zip/Archive/Common/HandlerOut.cpp \
    CPP/7zip/Archive/Common/ParseProperties.cpp \
    CPP/7zip/Archive/7z/7zCompressionMode.cpp \
    CPP/7zip/Archive/7z/7zDecode.cpp \
    CPP/7zip/Archive/7z/7zEncode.cpp \
    CPP/7zip/Archive/7z/7zExtract.cpp \
    CPP/7zip/Archive/7z/7zFolderInStream.cpp \
    CPP/7zip/Archive/7z/7zHandler.cpp \
    CPP/7zip/Archive/7z/7zHandlerOut.cpp \
    CPP/7zip/Archive/7z/7zHeader.cpp \
    CPP/7zip/Archive/7z/7zIn.cpp \
    CPP/7zip/Archive/7z/7zOut.cpp \
    CPP/7zip/Archive/7z/7zProperties.cpp \
    CPP/7zip/Archive/7z/7zSpecStream.cpp \
    CPP/7zip/Archive/7z/7zUpdate.cpp \
    CPP/7zip/Archive/7z/7zRegister.cpp

include $(BUILD_STATIC_LIBRARY)