APP_BUILD_SCRIPT :=  Android_static.mk
APP_CFLAGS := -g -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DZ7_EXTERNAL_CODECS -D_7ZIP_LARGE_PAGES
APP_CPPFLAGS := -g -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DZ7_EXTERNAL_CODECS -D_7ZIP_LARGE_PAGES
APP_STL := c++_static
APP_STRIP_MODE := none
APP_ABI := arm64-v8a x86_64